# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include: 
    - main

variables:
  uiName: 'dcw'
  uiBuild: '$(uiSource)/build'


pool:
  name: ubuntu-aws1

steps:

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm run-script build
  displayName: 'npm build'

- task: CmdLine@2
  inputs:
    script: |
      cd build
      sed -i 's/\/static/\/dashboards\mcdonalds\/\static/g' index.html
      mkdir -p login
      mkdir -p selectinfo
      mkdir -p dashboard
      cp index.html dashboard/
      cp index.html login/
      cp index.html selectinfo/

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultworkingDirectory)/build'
    includeRootFolder: true
    archiveType: 'tar'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).tar.gz'
    replaceExistingArchive: true



- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
