trigger:
  branches:
    include:
      - main

pool:
  name: ubuntu-aws1

steps:
  # Checkout the code from your repository
  - task: Checkout@1
    displayName: 'Checkout code'

  # Set up Node.js (required to run npm)
  - task: UseNode@1
    inputs:
      version: '22.x'
      addToPath: true
    displayName: 'Set up Node.js'

  # Install project dependencies
  - script: |
      npm install
    displayName: 'Install Dependencies'

  - script: |
      npm run test -- --watch=false --ci --reporters=dot
    displayName: 'Run Tests'

  # Build the React app for production
  - script: |
      npm run build
    displayName: 'Build React App'

  # Publish one artifact
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)/build'  # path to the build directory
      ArtifactName: 'drop'
      publishLocation: 'Container'

