# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include: 
    - main

variables:
  uiName: 'dcw'
  uiBuild: '$(uiSource)/build'

pool:
  name: ubuntu-aws1

steps:

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm run-script build
  displayName: 'npm build'

# Verify or manipulate build output (new command)
- script: |
    ls -l $(System.DefaultWorkingDirectory)/build
    echo "Build output verified"
  displayName: 'Verify build output'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultworkingDirectory)/build'
    includeRootFolder: true
    archiveType: 'tar'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).tar.gz'
    replaceExistingArchive: true


- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
